[general]
static=yes
writeprotect=no

[internal]

; тестовый номер
exten => 100,1,Answer()
 same => n,Playback(hello-world)
 same => n,Hangup()

; звонок 6001
exten => 6001,1,Dial(PJSIP/6001,15)
 same => n,VoiceMail(6001@default,u)
 same => n,Hangup()

; звонок 6002
exten => 6002,1,Dial(PJSIP/6002,15)
 same => n,VoiceMail(6002@default,u)
 same => n,Hangup()

; вход в голосовую почту
exten => *97,1,VoiceMailMain(${CALLERID(num)}@default)
 same => n,Hangup()